# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bcb97bc6c793a1e21e564eaab04451649ad6cf77cb696bd593c9f45a25671fd4ac80212711e9b869e254d2120328c206ba4ac4b37732fee8d2320ab0319828f

test:
  secret_key_base: 0bbef160fb99c92e0232c2a52925aaed7f7ba95fcf01e24090ee912e0be113fa2ff1855f24cc6f0db0728d75742152899b684cb396079d282eb160fa194f969c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
